DROP TABLE IF EXISTS `customer`;
create table customer (
        id integer generated by default as identity,
        email varchar(50) not null,
        name varchar(50) not null,
        phone varchar(50) not null,
        primary key (id)
 );